const constant = {
  SET_MATCHES_LIST: "SET_MATCHES_LIST",
  SET_SUMMONER_INFO: "SET_SUMMONER_INFO",
  SET_RANK_INFO: "SET_RANK_INFO",
  SET_SUMMONER_MASTER: "SET_SUMMONER_MASTER"
};

export default constant;
